name: Pytest Coverage Comment

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests and generate coverage
        run: |
          mkdir -p htmlcov
          pytest tests \
            --junitxml=pytest.xml \
            --cov=app \
            --cov-report=term-missing:skip-covered \
            --cov-report=html \
            > pytest-coverage.txt

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: html-coverage-report
          path: htmlcov

      - name: Comment coverage on PR
        uses: MishaKav/pytest-coverage-comment@v1.1.54
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
