name: Run Python Tests on EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run commands on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y python3.10 python3.12-venv python3.12-distutils curl unzip
            curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3.12

            # Clone repo (or pull latest if exists)
            if [ ! -d "myproject" ]; then
              git clone https://github.com/${{ github.repository }}.git myproject
            else
              cd myproject && git pull
            fi

            cd myproject

            # Install dependencies
            python3.10 -m pip install --upgrade pip
            if [ -f requirements.txt ]; then python3.10 -m pip install -r requirements.txt; fi

            # Run tests
            python3.10 -m pytest --junitxml=pytest.xml \
              --cov=calculator \
              --cov-report=term-missing:skip-covered \
              --cov-report=xml:coverage.xml \
              tests/ | tee pytest-coverage.txt

            python3.10 -m pytest --cov=calculator --cov-report=html:htmlcov tests/
